### ISSUE TITLE
why 

### ISSUE THREAD

**Issue by Chaoyue-Sun** [dontlearncpp/YOLOv8-with-RGB-D-and-AFFP#6]
Why is there no code? Do we have to wait for the article to be published before publishing it

**Comment by dontlearncpp** [comment]
Sorry, I uploaded the code before, but recently my server was upgraded and reinstalled, so I don't know why the code here is gone. I upload the code with git. I first time use it. I'll try to restore it in a few days.

**Comment by dontlearncpp** [comment]
![image](https://github.com/dontlearncpp/YOLOv8-with-RGB-D-and-AFFP/assets/103402250/d81e1cc0-881e-4b0d-8a10-0fcb27b5c500)
They are in different branchs, I will change the readme. Thank you
